pydata/numexpr

numexpr/tests/test_numexpr.py

When numpy hits version 1.10, string-based comparison of numpy version with minimum version will fail. Replacing with `pkg_resources.parse_version`.  I do not know if pkg_resources is available on all relevant versions. Others please verify.

Compare numpy version strings using pkg_resources.parse_version

---

numexpr/version.py
setup.py

This way pip and setup.py display the same behaviour and pip can query the name and version without actually doing the installation.

Add name and version to setup.py conditionally

---

AUTHORS.txt
numexpr/module.cpp

This would be fine on every processor I know, but is still a data race, and ThreadSanitizer reports it as such. Fix the concurrent write.
Also add "Google, Inc" to the authors file (sounds a bit ridiculous for such a small change, but is required by our policy for open source contributions).

Fix harmless data race.

---

RELEASE_NOTES.rst
numexpr/__init__.py
numexpr/tests/test_numexpr.py
numexpr/utils.py

This fixes issue  #161.
Relevant changes:
* extracted thread count computation in order to make it testable
* introduce OMP_NUM_THREADS

Support OMP_NUM_THREADS as fallback config variable

---

numexpr/tests/test_numexpr.py

It was mainly a matter of using byte literals.
I don't know why this issue has not been detected before

Fix issue #177

---

numexpr/str-two-way.hpp

This breaks newer compilers, because #ifdef was always defined, so win32/stdint was always being included, even on newer MSC versions.

Fix bad #ifdef for including stdint on windows.

---

numexpr/interpreter.cpp
numexpr/module.cpp
numexpr/module.hpp
numexpr/tests/test_numexpr.py

The attached unit test crashes quite reliably otherwise.
This change fixes the following crash in Pandas: https://stackoverflow.com/questions/25782912/pandas-and-numpy-thread-safety

Fix crash when evaluate() called from multiple threads

---

numexpr/necompiler.py

fixes https://github.com/pydata/numexpr/issues/80

added a fat lock around numexpr.evaluate

---

numexpr/expressions.py
numexpr/interp_body.cpp
numexpr/interpreter.cpp
numexpr/necompiler.py
numexpr/opcodes.hpp
numexpr/tests/test_numexpr.py

This PR adds two new reduction functions, `min` and `max`, which act like the numpy functions of the same name.
A few notes:
* Neither function supports complex numbers for now, but this could be added if necessary.
* I had to do some limbo to correctly initialize the output array, as there's no true identity value for min/max reductions. As of now, floating point min/max starts from NaN, while integer min/max starts from LONG_MAX/LONG_MIN, respectively.
* Other parts of the code assume that opcodes can be converted into single ASCII character (0-127), which puts a hard limit on the number of total opcodes. I did some shuffling to make the new opcodes fit, but any additional opcodes will require a bigger restructuring.
Finally, I've tagged this as a work in progress because I haven't done …

[WIP]: Add min and max reduction functions

---

numexpr/tests/test_numexpr.py

With recent numpy versions, using a float for the size argument will raise a TypeError.
This was causing the following two errors:
```
======================================================================
ERROR: test_reductions (numexpr.tests.test_numexpr.test_numexpr)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/numexpr-2.4.7.dev0-py2.7-linux-x86_64.egg/numexpr/tests/test_numexpr.py", line 96, in test_reductions
x = zeros(1e5) + .01  # checks issue #41
TypeError: 'float' object cannot be interpreted as an index
======================================================================
ERROR: test_reductions (numexpr.tests.test_numexpr.test_numexpr2) …
```

replace 1e5 (float) with 100000 (int)

---

numexpr/cpuinfo.py

Tested this on Windows with Python 2.7 and 3.5.
```
>python cpuinfo.py
CPU information: CPUInfoBase__get_nbits=32 getNCPUs=2 has_mmx is_32bit is_Intel is_i686
>py -3 cpuinfo.py
CPU information: CPUInfoBase__get_nbits=32 getNCPUs=2 has_mmx is_32bit is_Intel is_i686
```
```
> python -c "import cpuinfo, pprint; pprint.pprint(cpuinfo.cpu.info[0])"
{'Component Information': '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00',
'Configuration Data': '\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00',
'Family': 6,
'FeatureSet': 2687451135L,
'Identifier': u'x86 Family 6 Model 23 Stepping 10',
'Model': 23,
'Platform ID': 128,
'Previous Update Signature': '\x00\x00\x00\x00\x0c\n\x00\x00',
'Processor': '0',
'ProcessorNameString': u'Intel(R) Core(TM)2 Duo CPU     P8600 …
```

cpuinfo.py: Bring back printing CPU info on command line

---

numexpr/tests/test_numexpr.py

This PR adds a unittest for strides over columns of numpy.rec.arrays
(issue #210)
This unittest currently fails when using Intel MKL (VML): When using VML in numexpr "strides" are not respected. Arrays are assumed to be continuous when using VML, which is not the case when using columns of numpy.rec.array (as pytables does).
This might be fixed by unpacking the strided array into a temporary buffer that is continuous. But there might be an easier fix?
Output of unittest:
```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Numexpr version:   2.5.1.dev0
NumPy version:     1.10.4
Python version:    2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Dec  6 2015, 18:08:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Platform:          linux2-x86_64
AMD/Intel CPU?     True
VML …
```

Add unittest for strides over columns of numpy.rec.arrays

---

numexpr/necompiler.py
numexpr/tests/test_numexpr.py

In  ```necompiler.vml_functions``` the function ```abs()``` is defined as 'abs' while the parser uses numpy.absolute.
Testcase (this returns False on current master)
```python
import numexpr
from numexpr.necompiler import stringToExpression, getExprNames
def get_ex_uses_vml(expression):
mysig = [('f1', float)]
typemap = {'f1': float}
strexpr = stringToExpression(expression, typemap, {})
context = {}
names, ex_uses_vml = getExprNames(expression, context)
return ex_uses_vml
if __name__ == '__main__':
print "numexpr version: ", numexpr.__version__
print "VML: ", numexpr.get_vml_version()
expression = 'abs(f1)'
print expression, get_ex_uses_vml(expression)
```

change abs() from 'abs' to 'absolute' in necompiler.vmlfunctions

---

README.rst

Update appveyor link to pydata org.
Use shields.io instead of pypip.in (more reliable).
pypip.in is offline, it might come back and other have started new servers to replace it, but their reliability is unknown. https://github.com/badges/pypipins/issues/37

Fix shields in README

---

numexpr/interpreter.cpp
numexpr/numexpr_object.cpp

Added explicit casts to string constants to eliminate these compiler warnings.

MAINT: Elimited deprecated conversion from string constant to 'char *'

---

numexpr/interpreter.cpp
numexpr/module.cpp
numexpr/module.hpp

This eliminates numerous warnings like
warning: #warning "Using deprecated NumPy API, disable it by "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]

MAINT: Update to use current Numpy API

---

numexpr/expressions.py

It is logical for kind_rank to be a tuple since it's not intended to be modifiable.

type(kind_rank): list --> tuple

---

setup.py

Because numexpr/tests was being added as a subpackage without setup.py
there were the following two warnings while building the package
```
Warning: Assuming default configuration (numexpr/tests/{setup_tests,setup}.py was not found) 
Appending numexpr.tests configuration to numexpr
Ignoring attempt to set 'name' (from 'numexpr' to 'numexpr.tests')
```
The fix was to replace `config.add_subpackage('tests', 'numexpr/tests')`
with `config.add_data_dir('numexpr/tests')` akin how numpy itself adds test
directories in its setup.py

BUG: Eliminated warning about numexpr/tests

---

numexpr/cpuinfo.py

Currently cpuinfo.py is not able to detect POWER processor. This patch
simply adds the code into cpyinfo.py to detect the processor, its
version and it if supports Altivec extension.

Add Power processor initial support

---

numexpr/interp_body.cpp
numexpr/interpreter.cpp

Simply casting does not guarantee what might be considered a default
mathematical behaviour, since it might return non-expected results
(ie by truncating).
Apply llround to the pow result. That way, the result will be rounded
to the closest integer value after the long double operation.
Signed-off-by: Fernando Seiti Furusato <ferseiti@linux.vnet.ibm.com>

Fix pow result casting

---

numexpr/expressions.py

distutils.LooseVersion does not handle correctly RC versions

Better fix for gh-239

---

README.rst
numexpr/expressions.py
numexpr/functions.hpp
numexpr/msvc_function_stubs.hpp
numexpr/tests/test_numexpr.py

This pull request adds support for the `ceil()` and `floor()` functions which is partially mentioned in #89. E.g.,
```python
>>> import numpy as np, numexpr as ne
>>> A = np.array([0.5])
>>> ne.evaluate("ceil(A)")
array([ 1.])
>>> ne.evaluate("floor(A)")
array([ 0.])
>>> ne.evaluate("ceil(0.5)")
array(1.0)
>>> ne.evaluate("floor(0.5")
array(0.0)
```
I added the `numpy.ceil()` and `numpy.floor()` functions to the `functions` dictionary in *numexpr/expressions.py*. I also added `ceil_dd`, `ceil_ff`, `floor_dd`, and `floor_ff` using the `ceil()`, `ceilf()`, `floor()`, and `floorf()` functions to *numexpr/functions.hpp*. I believe these functions are all part of the C standard and are supported by glibc ([ceil](http://www.gnu.org/software/libc/manual/html_node/Rounding-Functions.html#index-cei …

Support ceil() and floor() functions

---

numexpr/functions.hpp
numexpr/necompiler.py

Fixes the following segfault(s) during tests:
```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Numexpr version:   2.6.3
NumPy version:     1.13.1
Python version:    3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
AMD/Intel CPU?     True
VML available?     True
VML/MKL version:   Intel(R) Math Kernel Library Version 2018.0.0 Product Build 20170720 for Intel(R) 64 architecture applications
Number of threads used by default: 8 (out of 12 detected cores)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
<snip>
test_scalar0_float32_b'aggressive'_b'1_ARG_FUNCS'_1134 (numexpr.tests.test_numexpr.suite.<locals>.TestExpressions) ...
Windows fatal exception: access violation
Current thread 0x00003160 (most recent …
```

Fix segaults with VML; Use VML functions for ceil and floor

---

RELEASING.txt

Update the release instructions to give more details on wheel build and
release procedure.
I think I discussed this with Francesc at some point, but I noticed that this
wasn't in the RELEASING document.

MRG: update release instructions for wheels

---

numexpr/tests/test_numexpr.py

The test bench did not run on Python 3 because of the usage of long,
a deprecated type that does not exist in Python 3. This patch creates
the equivament between Python 2's long and Python's 3 (automatically
growing) int. Fixes #296

Fixes test bench in Python 3

---

numexpr/interpreter.cpp
numexpr/module.cpp
numexpr/module.hpp

This PR avoids a segmentation fault when `pthread_cond_wait` is woken up spuriously. This fixes issue #306 for me.
I'd add tests, but I don't know how to trigger these spurious wakeups reliably.

Allow for spurious wakeup calls from pthread_cond_wait.

---

numexpr/cpuinfo.py

These line continuation characters were tripping up python 3.7 on Windows (only this platform - mac and linux, as well as all other Python versions on Windows were fine.  Go figure.
Also, this particular line seemed fishy:
```
and (self.has_sse3() and not self.has_ssse3())
```
isn't that always false, by definition, because they can't both be true?  I looked it up online, and nocona has sse3, so I tried to adjust the logic accordingly (keep just self.has_sse3).

tweak line continuation in cpuinfo (py37 win problem)

---

.travis.yml

Travis-CI has added support for ARM64. Added ARM64 job in Travis-CI.

Adding Travis-Ci Supprt for Arm64

---

numexpr/module.cpp
numexpr/tests/test_numexpr.py
numexpr/utils.py

Adds `get_vml_num_threads` to match `set_vml_num_threads`
It's nice to be able to inspect as well as set these values, especially since some libraries seem to be changing these under the hood (per: https://github.com/PyTables/PyTables/issues/786).

Add Getter for VML Thread Count

---

.github/workflows/build.yml

Merge `cibuildwheel` wheel builds into master.

Cibuildwheel

---

numexpr/tests/test_numexpr.py

Quick fix for two SPARC64 failures in these tests.
https://buildd.debian.org/status/fetch.php?pkg=numexpr&arch=sparc64&ver=2.7.2-1&stamp=1609580013&raw=0

Adapt the init_num_threads related tests for SPARC64 platform #373

---

setup.py

/O2 compiler option is not valid for gcc or clang in mingw.
So, check if the python is used in MSVC environment.

Fix build with mingw python

---

.github/workflows/build.yml

This creates wheels for Apple silicon arm64 and also simplifies the build. You don't need to list all python versions as cibw will take care of it.

Add support for Apple silicon and simplify build

---

numexpr/expressions.py
numexpr/necompiler.py
numexpr/tests/test_numexpr.py

This pull requested fixes issue with constant duplication (#414).
But there are also some other minor fixes:
- Properly parse `where_xxxx` instructions in disassembler (do not drop 4-th argument)
- Allow `nan` floating point constant construction
- Allow `np.float32(v)` constants (do not promote those to `double`)
Note that one can only use those constants when building expression with python classes directly, parsing `nan` or `float32` out of textual representation is not enabled by this PR.
Closes #414

Fix constant dupes

---

numexpr/expressions.py
numexpr/tests/test_numexpr.py
requirements.txt

The numpy requirement is greater than 1.13. 
Numpy 1.12 is quite old at this stage and most have even moved to 1.19 at this stage

Remove _np_version_forbids_neg_powint

---

numexpr/interpreter.cpp

This suppresses a warning about setting the value when it's value is never used.

Don't define/set ex_uses_vml if USE_VML is not defined

---

numexpr/module.cpp
numexpr/win32/pthread.h

Applications that embed python, or use platform-specific python extensions, may use signals in a way that is currently affected by `numexpr` launching threads.
For example, it is not uncommon for an application main loop to block signals when busy, then unblock those signals while waiting for IO. (see the sigmask argument to `ppoll(2)`)
Signals that arrive during `ppoll(2)` will interrupt the system call, and allow the application to handle any consequences of that signal arriving.  Normally (in a single threaded process), on delivery of an externally generated signal such as SIGALRM, SIGCHLD, SIGIO the main loop will be awoken. IF the thread is otherwise busy, then the signal will be maintained as pending, and will be delivered when the application next enters its idle state with `ppoll` …

Block signal delivery to numexpr-spawned threads

---

setup.py

numpy parses libraries in site.cfg by [splitting on comma](https://github.com/numpy/numpy/blob/7fc72776b972bfbfdb909e4b15feb0308cf8adba/site.cfg.example#L19C1-L24). We want to maintain compatibility with that, but we've already established `os.pathname` by accident. To minimize breakages, we support both.
Fixes #407

Fix setup.py to respect numpy's parsing of libraries in site.cfg

---

numexpr3/ne3compiler.py

I tried to add functions (minimum, maximum) to numexpr2 and found that first, there are no more opcodes available, and second that these functions are already in the 3.0 branch.  So I'm upgrading my project to use 3.0 and this is the only problem I had.
Thank you for this repo - it's awesome.

Added local_dict to NumExpr constructor call in evaluate.

---

numexpr/interpreter.cpp

Fixes a compile error when building with MKL/VML:
```
numexpr/interpreter.cpp(996): error C2144: syntax error: 'int' should be preceded by ';'
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

Fix syntax error when building with USE_VML

---

numexpr/tests/test_numexpr.py

np.alltrue is recently deprecated:
https://numpy.org/doc/stable/release/1.25.0-notes.html#deprecations.
I left np.all aliased to alltrue because `all` is also the name of a builtin, and some linters complain if you overwrite a builtin.

Remove usage of deprecated np.alltrue().

---

numexpr/necompiler.py
numexpr/tests/test_numexpr.py

This PR modifies the sanitize regular expression to access digits after the `.` with scientific notation.
closes #449, related to https://github.com/pydata/numexpr/issues/442#issuecomment-1685097531

Fix scientific notation support

---

numexpr/necompiler.py

Don't reject double underscores that are not at the start or end of a variable name ([pandas uses those](https://ci.debian.net/data/autopkgtest/testing/amd64/p/pandas/38088122/log.gz)), or [scientific-notation numbers with digits after the decimal point](https://ci.debian.net/data/autopkgtest/testing/arm64/p/pyfai/38080705/log.gz).

sanitization: reduce unnecessary rejections

---

.github/workflows/build.yml
ANNOUNCE.rst
README.rst
RELEASE_NOTES.rst
numexpr/tests/test_numexpr.py
setup.cfg

This is a proposal for releasing 2.8.7 with support for Python 3.12 wheels (Python 3.7 and 3.8 wheels are not being generated anymore; IMO supporting 4 versions is enough, and the standard for other projects like NumPy).  Also, and following [NumPy 1.25 decision](https://github.com/numpy/numpy/issues/20089), this PR generates wheels for musllinux too, but only for x86_64, as building them for arm64 takes way too long (this is the same decision as NumPy folks took as well).

Release 2.8.7

---

numexpr/necompiler.py

When evaluate an expression, it first validate and then re_evaluate, while re_evaluate doesn't take global_dict as an argument causing getArguments raises KeyError.
This PR fixes issue https://github.com/pydata/numexpr/issues/456

Fix re_evaluate not taking global_dict as argument

---

numexpr/complex_functions.hpp
numexpr/interp_body.cpp
numexpr/interpreter.cpp

Since numpy uses new complex type, the current usage of npy_cdouble (in complex_functions.hpp) is no longer supported.
And in fact numexpr doesn't have to use numpy's complex type, so I replaced npy_cdouble with C++11 std::complex<double>.
This fixes issue https://github.com/pydata/numexpr/issues/458.

fix: replace npy_cdouble with C++ complex

---

numexpr/necompiler.py

Commit https://github.com/pydata/numexpr/commit/397cc98359301d0e7b96aaa6d3c79419d1d4f189 introduces sanitizer to input string, but it will forbid the usage of imaginary unit `j` like this:
```python
import numexpr as ne
ne.evaluate('1.5j')
```
So I slightly changed the regular expression to allow this usage.
This should fix issue https://github.com/pydata/numexpr/issues/459

fix sanitizer forbid usage of \d+.\d*j

---

numexpr/interpreter.cpp
numexpr/numexpr_config.hpp

According to issue  https://github.com/pydata/numexpr/issues/460 NPY_MAXARGS will become a runtime constant so not suitable for stack array size, but should be kept for runtime check.
So I added NE_MAXARGS and currently it's 64 which is enough and if numpy raise NPY_MAXARGS in the future we should notice this and raise it accordingly.

add NE_MAXARGS for future numpy change NPY_MAXARGS

---

numexpr/tests/test_numexpr.py

since `numpy` will remove `np.complex_` so we should replace `complex_` with `cdouble` in `numexpr.test` module

replace importing complex_ with cdouble for numpy2

---

numexpr/necompiler.py
numexpr/tests/test_numexpr.py

Sanitizer will forbid forbidden characters to be used within quotes, which is unnecessary.
I passed this by firstly removing content within quotes and then let regular expression to match the blacked list.
I also added corresponding tests for this and a previous change https://github.com/pydata/numexpr/pull/462
This should fix issue https://github.com/pydata/numexpr/issues/468

fix sanitizer forbid colon within quotes

---

numexpr/interpreter.cpp

Not clearly whether it's bug on `numexpr` side or `pypy` side, but when using `pypy`, sometimes function `Numexpr_Run(PyObject *self, PyObject *args, PyObject *kwds)` gets no dictionary arguments but pointer `kwds` is still non-null. 
So add a further check of the size of dictionary `kwds`. It won't affect the performance since it's only one-time check.
This should fix issue https://github.com/pydata/numexpr/issues/463, although not all errors could be eliminated for `pypy` because `sys` module in `pypy` seems not to have attribute `getrefcount` which is used when testing.

fix: under pypy, when no dict args given, kwds is non-null

---

numexpr/tests/test_numexpr.py

PyPy does not provide `sys.getrefcount()` method due to a different GC implementation, so skip the relevant test when running on PyPy.

Skip test requiring sys.getrefcount() on PyPy

---

numexpr/tests/test_numexpr.py
numexpr/utils.py

unsetting the variable like this is not uncommon but this will raise here unfortunately
This circumvents the issue

Avoid erroring when OMP_NUM_THREADS is empty string

---

README.rst

_Hello everyone,_
A raster PyPI version badge looks blurry at scales different from 100%, so I believe it's worth switching to a vector badge which looks fine at any scale.
Image below shows how a raster badge looks versus a vector one at 170% scale on my machine.
_Best regards!_

🖌️ Use a vector version badge

---

numexpr/interpreter.cpp
pyproject.toml
requirements.txt
setup.py

I noticed this while testing a downstream package that the following `ImportError` was raised from NumPy 2.0.0rc1 pointing to numexpr:
<details><summary>Traceback</summary>
```python-traceback
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0.dev0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
Traceback (most recent call last):  File "/opt/hostedtoolcache/Python/3.12.2/x64/bin/pytest", line 8, in <module>
sys.exit(console_main())
File …
```

BLD: build with numpy instead of oldest-supported-numpy

---

numexpr/interpreter.cpp

I have build locally without build isolation to test this.
This is picking up on the comments on the PR.  I have not removed the explicit use of target version, although I tend to agree it is probably easier to just remove it, even if it is maybe slightly less explicit (means conda doesn't have to wonder about it).  OTOH, it is nicely explicit.

MAINT: Allow building with NumPy 1.x locally

---

numexpr/necompiler.py

The FrameLocalsProxy object (PEP 667) cannot be cleared.
Fixes https://github.com/pydata/numexpr/issues/488

Fix necompiler.getArguments() on Python 3.13.0b1

---

.github/workflows/build.yml
numexpr/tests/test_numexpr.py

+ add Python 3.13 to the CI.
Closes #486

unittest.makeSuite() has been removed from Python 3.13

---

bench/large_array_vs_numpy.py
numexpr/necompiler.py
numexpr/tests/test_numexpr.py
numexpr/utils.py

As the title (ref: https://github.com/pydata/numexpr/issues/494),  the change:
- replace `_numexpr_last` with a dictionary like object aware of context
reasoning:
- I do like the feature of `re-evaluate` and want it to stay the safe as well
-  open the pathways to `async` re/evaluate, which is to further cater to my specific user case.
benchmark case:
It's based on my reality that most of time, I got large amount of data and only chunks of data can fit into memory, most of my cpus are idling when io (especially i) happens. If the data can fit into memory and cpus are fully utilized, I guess it doesn't make much difference between threading with `numpy` by chunks vs `numexpr`.  Certainly I can implement what `numexpr` can achieve by further chunking each chunk, but why? Specifically I use …

Support multithreading

---

.github/workflows/build.yml

See https://github.com/pydata/numexpr/issues/503#issuecomment-2735343819

Use native aarch64 CI builders

---

bench/free_threading.py
numexpr/necompiler.py

Add a benchmark/example for numexpr usage under free-threading conditions

---

.github/workflows/build.yml
numexpr/tests/conftest.py
pyproject.toml

I made a couple adjustments to `cibuildwheel`'s configuration, following upstream changes.
Notably:
- unsupported python versions don't need to be explicitly skipped; `project.requires-python` is already taken into account
- `pypy` wheels are not enabled by default any more since `cibuildwheel` `3.0.0`, so stop skipping them explicitly
Also note, as a point of detail, that `CIBW_ENABLE=free-threading-cpython` is *still* necessary for `cp313t`, but it *isn't* for `cp314t`.

WHL: upgrade cibuildwheel, add `cp314` wheels

---

.github/workflows/build.yml
pyproject.toml

Based of #517
I noticed at least one reason for not building these wheels was outdated (numpy *does* provide `musllinux-x86_64` as well as `musllinux-aarch64` wheels these days), so I wanted to give it a spin (pun intended)

WHL: enable musllinux wheels

---

numexpr/numexpr_config.hpp

Fix build on NetBSD with gcc 12.
